name: Run Pre-Commit Checks

on:
  push:

jobs:
  Pre-commit-checks:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
